config/routes.rb
Rails.application.routes.draw do
  root to: 'homes#top'
  devise_for :users
  devise_scope :user do
    post 'users/guest_sign_in' => 'users/sessions#new_guest'
  end

  get 'search' => "searchs#search", as: 'search'
  get 'search/tag/:tag_name' => "searchs#tag_search", as: 'tag_search'

  get 'mypage' => 'users#mypage', as: 'mypage'
  patch 'withdraw' => 'users#withdraw'
  get 'mypage/edit' => 'users#edit'
  patch 'mypage/update' => 'users#update'

  resources :users, only: [:show], param: :name do
    resource :relationship, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end

  put 'new/:id/post' => 'notes#post', as: 'notes_post'
  get 'favorite-notes' => 'users#favorite', as: 'favorite_notes'

  get 'notes/draft' => 'notes#draft', as: 'notes_draft'

  resources :notes do
    resources :note_comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
    resources :spots, only: [:new, :create, :destroy]
  end

  resources :notifications, only: :index
end

app/models/spot.rb
class Spot < ApplicationRecord
  belongs_to :note

  validates :note_id, presence: true
  validates :address, presence: true, length: { minimum: 2, maximum: 20 }
  validates :body, presence: true, length: { minimum: 2, maximum: 100 }

  geocoded_by :address
  before_validation :geocode
end

app/controllers/spots_controller.rb
class SpotsController < ApplicationController
  before_action :authenticate_user!

  def new
    @spot = Spot.new
    @note = Note.find(params[:note_id])
  end

  def create
    @spot = Spot.new(spot_params)
    @note = Note.find(params[:note_id])
    @spot.note_id = @note.id
    render 'error' unless @spot.save
  end

  def destroy
    @note = Note.find(params[:note_id])
    Spot.find(params[:id]).destroy
  end

  private

  def spot_params
    params.require(:spot).permit(:address, :latitude, :longitude, :title, :body)
  end
end

app/helpers/spots_helper.rb
module SpotsHelper
end

app/views/spots/_form.html.erb
<div class="container my-5">
  <div id="spot_error">
    <%= render 'layouts/errors', model: @spot %>
  </div>
  <div class="row mb-3">
    <div class="col-5">
      <div>
        <div class="text-center"><b>ステップ1</b></div>
        <div class="text-center">Spot名を入力して検索(20字以内)</br>地図にピンが表示されます</div>
        <input id="address" type="textbox" class="col-12 mb-3" placeholder="Spot名を入力→検索">
        <input type="button" value="検索" onclick="codeAddress()" class='btn btn-sm btn-light btn-outline-dark col-12'>
      </div>
    </div>
    <div class="col-2">
      <div class="mt-5 text-center">
        <i class="fas fa-chevron-right fa-3x" style="color: #808080"></i></br>
      </div>
    </div>
    <div class="col-5">
      <div class="text-center"><b>ステップ2</b></div>
      <div class="text-center">説明を入力(100字以内)</div>
      <div>
        <%= form_with model:[note, spot] do |f| %>
          <!-- 検索値を隠しデータとして送信-->
          <input type="hidden" name="spot[address]" id="hidden_address">
          <input type="hidden" name="spot[latitude]" id="hidden_latitude">
          <input type="hidden" name="spot[longitude]" id="hidden_longitude">
          <div  class="form-group">
            <%= f.text_area :body, rows: '3', class:"form-control", placeholder: "記入後、保存を押してください" %>
          </div>
          <%= f.submit "保存", class:"btn btn-sm btn-outline-dark btn-light col-12" %>
        <% end %>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-6">
      <div id="map"></div>
      <script>
        let map
        let geocoder
        let marker

        function initMap() {
          geocoder = new google.maps.Geocoder()
          map = new google.maps.Map(document.getElementById('map'), {
            <% if note.spots.exists? %>
            center: {
              lat: <%= note.spots[0].latitude %>,
              lng: <%= note.spots[0].longitude %>
            },
            zoom: 12
            <% else %>
            center: {
              lat: 35.6585848,
              lng: 139.7432389
            },
            zoom: 12
            <% end %>
          });
          
          <% note.spots.each do |spot| %>
            var spot_marker = new google.maps.Marker({
              position:{lat: <%= spot.latitude %>, lng: <%= spot.longitude %>},
              map: map,
            });
            var infoWindow = new google.maps.InfoWindow({
              content: "<%= spot.address %>"
            });
            infoWindow.open(map, spot_marker);
          <% end %>
        }

        function codeAddress(){
          let inputAddress = document.getElementById('address').value;
          
          geocoder.geocode( { 'address': inputAddress}, function(results, status) {
            if (status == 'OK') {
              map.setCenter(results[0].geometry.location);
              
              if(marker != null){
                marker.setMap(null);
              }
              marker = null;
              
              marker = new google.maps.Marker({
                map: map,
                position: results[0].geometry.location
              });

              let hidden_address = document.getElementById('hidden_address');
              hidden_address.setAttribute("value", inputAddress);
              
              let hidden_latitude = document.getElementById('hidden_latitude');
              hidden_latitude.setAttribute("value", marker.position.lat());
              
              let hidden_longitude = document.getElementById('hidden_longitude');
              hidden_longitude.setAttribute("value", marker.position.lng())
              
              var infoWindow = new google.maps.InfoWindow({
                content: inputAddress
              });
              infoWindow.open(map, marker);

            } else {
              alert('該当する結果がありません：' + status);
            }
          });
        }
      </script>
      <script async defer src="https://maps.googleapis.com/maps/api/js?v=3.exp&key=<%= ENV['GOOGLE_API_KEY'] %>&callback=initMap"></script>
    </div>
    <div class="col-5 ml-3" id="spot-index">
      <%= render "spots/index", note: note %>
    </div>
  </div>
</div>

app/views/spots/_index.html.erb
<% note.spots.each do |spot| %>
  <div class="row mb-2">
    <div class="col-1">
      <i class="far fa-bookmark fa-2x float-right"></i>
    </div>
    <div class="col-10">
      <div class="spot-name"><b><%= spot.address %></b></div>
      <div class="show-spot-body mt-2 col-12"><%= spot.body %></div>
      <div class="text-right">
        <%= link_to "削除", note_spot_path(note.id, spot.id), method: :delete, class:'btn btn-sm btn-secondary', remote: true %>
      </div>
    </div>
  </div>
<% end %>

app/views/spots/create.js.erb
$('#spot-index').html("<%= j(render "spots/index", note: @note) %>");
$("#spot_error").html("<%= j(render 'layouts/errors', model: @spot) %>");
$("textarea").val('');
$("#address").val('');
$("#hidden_address").val('');

app/views/spots/destroy.js.erb
$('#spot-index').html("<%= j(render "spots/index", note: @note) %>");

app/views/spots/error.js.erb
$("#spot_error").html("<%= j(render 'layouts/errors', model: @spot) %>");

app/views/spots/new.html.erb
<div class="container mt-5 pb-5">
  <div class="row">
    <div class="col-10 m-auto">
      <h1><b style="color: #E08504;">S</b>pot</h1>
      <p>スポットを追加</p>
      <%= render 'spots/form', spot: @spot, note: @note  %>
      <% if @note.posted == false %>
        <div class="actions col-3 mx-auto mb-3">
          <%= link_to "投稿", notes_post_path(@note), method: :put, class: "col-12 btn btn-sm btn-light btn-outline-dark" %>
        </div>
        <div class="actions col-3 mx-auto">
          <%= link_to "下書きに保存", notes_draft_path, class: "col-12 btn btn-sm btn-light btn-outline-dark" %>
        </div>
      <% else %>
        <div class="actions col-3 mx-auto">
          <%= link_to "追加完了", notes_post_path(@note), method: :put, class: "col-12 btn btn-sm btn-light btn-outline-dark" %>
        </div>
      <% end %>
    </div>
  </div>
</div>