config/routes.rb
Rails.application.routes.draw do
  root to: 'homes#top'
  devise_for :users
  devise_scope :user do
    post 'users/guest_sign_in' => 'users/sessions#new_guest'
  end

  get 'search' => "searchs#search", as: 'search'
  get 'search/tag/:tag_name' => "searchs#tag_search", as: 'tag_search'

  get 'mypage' => 'users#mypage', as: 'mypage'
  patch 'withdraw' => 'users#withdraw'
  get 'mypage/edit' => 'users#edit'
  patch 'mypage/update' => 'users#update'

  resources :users, only: [:show], param: :name do
    resource :relationship, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end

  put 'new/:id/post' => 'notes#post', as: 'notes_post'
  get 'favorite-notes' => 'users#favorite', as: 'favorite_notes'

  get 'notes/draft' => 'notes#draft', as: 'notes_draft'

  resources :notes do
    resources :note_comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
    resources :spots, only: [:new, :create, :destroy]
  end

  resources :notifications, only: :index
end

app/models/note.rb
class Note < ApplicationRecord
  belongs_to :user
  has_many :spots, dependent: :destroy
  has_many :note_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :note_tags, dependent: :destroy
  has_many :tags, through: :note_tags
  has_many :notifications, dependent: :destroy
  attachment :image

  validates :title, presence: true, length: { minimum: 2, maximum: 20 }
  validates :stay, presence: true
  validates :body, presence: true, length: { minimum: 2, maximum: 50 }
  validates :status, presence: true

  enum stay: { 'day_trip': 0, '1n_2d': 1, '2n_3d': 2, '3n_4d': 3, '4n_5d': 4 }

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

  # タグの作成と編集
  def save_tag(sent_tags)
    current_tags = tags.pluck(:tag_name) unless tags.nil?
    old_tags = current_tags - sent_tags
    new_tags = sent_tags - current_tags

    old_tags.each do |old|
      tags.delete Tag.find_by(tag_name: old)
    end

    new_tags.each do |new|
      new_note_tag = Tag.find_or_create_by(tag_name: new)
      tags << new_note_tag
    end
  end

  # 検索欄
  def self.search_for(word)
    Note.where('title like? OR body like?', "%#{word}%", "%#{word}")
  end

  # Topページのいいねの多い投稿を表示(週間ランキング)
  def self.best_note
    find(Favorite.group(:note_id).where(created_at: Time.current.all_week).order(Arel.sql('count(note_id) desc')).limit(3).pluck(:note_id))
  end

  # ユーザーの全投稿とタグの取り出し
  def self.user_notes_tag(user)
    includes(:tags).where(user_id: user.id)
  end

  # 公開投稿を選び、最新順に並び替える(index)
  def self.public_note_index
    Note.includes(:user, :spots, :tags).where(posted: true, status: 0).order(created_at: :desc)
  end

  # 公開投稿を選び、最新順に並び替える(show)
  def self.public_note
    Note.includes(:spots, :tags).where(posted: true, status: 0).order(created_at: :desc)
  end

  # 非公開、公開投稿を選び、最新順に並び替える(mypage)
  def self.private_public_note
    Note.includes(:spots, :tags).where(posted: true).order(created_at: :desc)
  end

  # いいね通知作成
  def create_notification_like(current_user)
    temp = Notification.where(["visitor_id = ? and visited_id = ? and note_id = ? and action = ? ", current_user.id, user_id, id, 'like'])
    if temp.blank?
      notification = current_user.active_notifications.new(
        note_id: id,
        visited_id: user_id,
        action: 'like'
      )
      # 自分の投稿に対するいいねの場合は、通知済みとする
      if notification.visitor_id == notification.visited_id
        notification.checked = true
      end
      if notification.valid?
        notification.save
      end
    end
  end

  def save_notification_comment(current_user, note_comment_id, visited_id)
    # コメントは複数回することが考えられるため、１つの投稿に複数回通知する
    notification = current_user.active_notifications.new(
      note_id: id,
      note_comment_id: note_comment_id,
      visited_id: visited_id,
      action: 'comment'
    )
    # 自分の投稿に対するコメントの場合は、通知済みとする
    if notification.visitor_id == notification.visited_id
      notification.checked = true
    end
    if notification.valid?
      notification.save
    end
  end
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :authenticate_user!

  def index
    @notes = Note.public_note_index.page(params[:page]).per(4)
    @tags = Tag.order(created_at: :desc).first(100)
  end

  def draft
    @user = User.find(current_user.id)
    @user_notes = Note.user_notes_tag(@user)
    @notes = current_user.notes.where(posted: false).page(params[:page]).per(4)
  end

  def show
    @note = Note.includes(:tags, :user).find(params[:id])
    @note_comment = NoteComment.new
    @user = User.find(@note.user_id)
    @user_notes = Note.user_notes_tag(@user)
    @note_comments = @note.note_comments.includes(:user).all
  end

  def new
    @note = Note.new
  end

  def create
    @user = User.find(current_user.id)
    @note = current_user.notes.new(note_params)
    tag_list = params[:note][:tag_name].split(/[[:blank:]]+/)
    if @note.save
      # save_tagはnote.rbにて定義
      @note.save_tag(tag_list)
      redirect_to new_note_spot_path(note_id: @note.id)
    else
      render 'new'
    end
  end

  def edit
    @note = Note.find(params[:id])
    @tag_list = @note.tags.pluck(:tag_name).join(' ')
    if @note.user == current_user
      render 'edit'
    else
      redirect_to note_path(@note)
    end
  end

  def update
    @note = Note.find(params[:id])
    tag_list = params[:note][:tag_name].split(/[[:blank:]]+/)
    if @note.update(note_params)
      @note.save_tag(tag_list)
      redirect_to note_path(@note)
    else
      @user = User.find(current_user.id)
      @user_notes = Note.includes(:tags).where(user_id: @user.id).all
      render 'edit'
    end
  end

  def post
    note = Note.find(params[:id])
    note.update(posted: true)
    redirect_to note_path(note.id)
  end

  def destroy
    note = Note.find(params[:id])
    note.destroy
    redirect_to mypage_path
  end

  private

  def note_params
    params.require(:note).permit(:title, :stays, :body, :status, :image)
  end
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/views/notes/_edit.html.erb
<div class="my-3">
  <% if @note.errors.any? %>
    <div><i class="fas fa-exclamation"></i> <%= @note.errors.count %>件のエラーが発生しました</div>
    <div class="border border-danger col-6">
      <% @note.errors.full_messages.each do |message| %>
        <%= message %></br>
      <% end %>
    </div>
  <% end %>
  <%= form_with model:note, local: true do |f| %>
  <div class="my-3 border-bottom row">
    <%= f.label "タイトル", class:"col-4 text-center" %>
    <%= f.text_field :title, autofocus: true, autocomplete: "title", class:"col-6" %>
  </div>
  <div class="my-3 border-bottom row">
    <%= f.label "宿泊数", class:"col-4 text-center" %>
    <%= f.select :stay, Note.stays.keys.map {|k| [I18n.t("enums.note.stay.#{k}"), k]}, {prompt: "日程を選択してください"}, class:"col-6" %>
  </div>
  <div class="my-3 border-bottom row">
    <%= f.label "画像", class:"col-4 text-center" %>
    <%= f.attachment_field :image, class:"col-6" %>
  </div>
  <div class="my-3 border-bottom row">
    <%= f.label "説明", class:"col-4 text-center" %>
    <%= f.text_area :body, class:"col-6" %>
  </div>
  <div class="my-3 border-bottom row">
    <div class="col-4 text-center">
      <%= f.label "タグ付け" %>
    </div>
    <div class="col-6">
      <div class="row">
        スペースを入力すると複数登録出来ます</br>
        例:金沢 グルメ 城</br>
      </div>
      <div class="row">
        <%= f.text_area :tag_name, value: tag_list , class:"col-12" %>
      </div>
    </div>
  </div>
  <div class="my-3 text-center">
    <div><%= f.radio_button :status, 1, checked: true %>非公開</div>
    <div><%= f.radio_button :status, 0 %>全ユーザーに公開</div>
  </div>
  <div class="actions col-3 mx-auto">
    <% if @note.posted == false %>
      <%= link_to "投稿", notes_post_path(@note), method: :put, class: "col-12 btn btn-sm btn-light btn-outline-dark mb-3" %>
      <%= f.submit "編集を保存する", class: "btn-block btn-sm btn btn-light btn-outline-dark" %>
    <% else %>
      <%= f.submit "編集を保存する", class: "btn-block btn-sm btn btn-light btn-outline-dark  mb-3" %>
    <% end %>
  </div>
  <% end %>
</div>

app/views/notes/_form.html.erb
<div class="my-3">
  <% if @note.errors.any? %>
    <div><i class="fas fa-exclamation"></i> <%= @note.errors.count %>件のエラーが発生しました</div>
    <div class="border border-danger col-6">
      <% @note.errors.full_messages.each do |message| %>
        <%= message %></br>
      <% end %>
    </div>
  <% end %>
  <%= form_with model:note, local: true do |f| %>
  <div class="my-3 border-bottom row">
    <%= f.label "タイトル", class:"col-4 text-center" %>
    <%= f.text_field :title, autofocus: true, autocomplete: "title", class:"col-6" %>
  </div>
  <div class="my-3 border-bottom row">
    <%= f.label "宿泊数", class:"col-4 text-center" %>
    <%= f.select :stay, Note.stays.keys.map {|k| [I18n.t("enums.note.stay.#{k}"), k]}, {prompt: "日程を選択してください"}, class:"col-6" %>
  </div>
  <div class="my-3 border-bottom row">
    <%= f.label "画像", class:"col-4 text-center" %>
    <%= f.attachment_field :image, class:"col-6" %>
  </div>
  <div class="my-3 border-bottom row">
    <%= f.label "本文", class:"col-4 text-center" %>
    <%= f.text_area :body, class:"col-6" %>
  </div>
  <div class="my-3 border-bottom row">
    <div class="col-4 text-center">
      <%= f.label "タグ付け" %>
    </div>
    <div class="col-6">
      <div class="row">
        スペースを入力すると複数登録出来ます</br>
        例:金沢 グルメ 城</br>
      </div>
      <div class="row">
        <%= f.text_area :tag_name, class:"col-12" %>
      </div>
    </div>
  </div>
  <div class="my-3 text-center">
    <div><%= f.radio_button :status, 1, checked: true %>非公開</div>
    <div><%= f.radio_button :status, 0 %>全ユーザーに公開</div>
  </div>
  <div class="actions col-3 mx-auto">
    <%= f.submit "Spotを追加", class: "btn-block btn-sm btn btn-light btn-outline-dark" %>
  </div>
  <% end %>
</div>

app/views/notes/_index.html.erb
  <div class="row m-auto">
    <% if notes.count == 0 %>
      <div>公開された投稿はありません</div>
    <% else %>
      <% notes.each do |note| %>
        <div class="col-11 m-3 border rounded bg-white">
          <div class="row mt-2 ml-2 pb-2 border-bottom">
            <div class="profile-img">
              <%= attachment_image_tag note.user, :profile_image, format: 'jpg', fallback: "no_image.jpg" %>
            </div>
            <div class="d-flex align-items-center ml-2">
              <%= link_to note.user.name, user_path(note.user.name) %>
            </div>
            <div class="text-right col-10 my-2">
              <div>コメント：<%= note.note_comments.count %>　/　
              <span id="favorite_button<%= note.id %>"><%= render "favorites/favorite-botton", note: note %></span></div>
            </div>
          </div>
          
          <div class="row mb-1 border-bottom">
            <div class="m-3 index-note-img">
              <%= attachment_image_tag note, :image, fallback: "no_image.jpg" %>
            </div>
            <div class="col-7 my-3">
              <div class="row mb-3">
                <div class="col-12 tag">
                  タグ<i class="fas fa-tag"></i>：
                  <% note.tags.each do |tag| %>
                    <%= link_to tag.tag_name, tag_search_path(tag.tag_name) %>
                  <% end %>
                </div>
              </div>
              <div>
                <% note.spots.first(2).each do |spot| %>
                <div class="row mb-2">
                  <div class="col-1">
                    <i class="far fa-bookmark fa-2x"></i>
                  </div>
                  <div class="col-11">
                    <div class="spot-name"><b><%= spot.address %></b></div>
                    <div class="spot-body"><%= spot.body %></div>
                  </div>
                </div>
                <% end %>
                <% if note.spots.count > 2 %>
                  <div><%= link_to "▼more", note_path(note.id) %></div>
                <% end %>
              </div>
            </div>
          </div>
      
          <div class="text-center">
            <% if note.user == current_user %>
              <%= link_to "投稿詳細", note_path(note.id) %>　/　
              <%= link_to "削除", note_path(note.id), method: :delete %>
            <% else %>
              <%= link_to "投稿詳細", note_path(note.id) %>
            <% end %>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>

app/views/notes/_show.html.erb
<div class="ml-3">
  <% if note.user == current_user %>
    <%= link_to "編集", edit_note_path(note.id) %>/
    <%= link_to "Spot追加", new_note_spot_path(note_id: note.id), data: {"turbolinks" => false} %>/
    <%= link_to "削除", note_path(note.id), method: :delete %>
  <% end %>
  
  <div class="row my-3">
    <div class="col-8">
      <h1><%= note.title %></h1>
    </div>
    <div class="col-4">
      <span id="comment_quantity">コメント：<%= note.note_comments.count %>　/　</span>
      <span id="favorite_button<%= note.id %>"><%= render "favorites/favorite-botton", note: @note %></span>
    </div>
  </div>
  <div class="row ml-3">
    <div class="show-note-img p-2">
      <%= attachment_image_tag note, :image, format: 'jpg', fallback: "no_image.jpg" %>
    </div>
    <div class="col-8 ml-2 p-2">
      <table class="table">
        <tbody>
          <tr>
            <td nowrap>日程：</td>
            <td><%= note.stay_i18n %></td>
          </tr>
          <tr>
            <td>本文：</td>
            <td><%= note.body %></td>
          </tr>
          <tr>
            <td>タグ：</td>
            <td>
              <% note.tags.each do |tag| %>
                <%= tag.tag_name %>
              <% end %>
            </td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
</div>

<div class="mt-4 ml-3">
  <% if note.spots.exists? %>
  <div class="row">
    <div class="col-6 mr-3">
      <div id="map"></div>
      <script>
        function initMap() {
          let geocoder = new google.maps.Geocoder()
          let map = new google.maps.Map(document.getElementById('map'), {
            center: {
              lat: <%= note.spots[0].latitude %>,
              lng: <%= note.spots[0].longitude %>
            },
            zoom: 12
          });
          
          <% note.spots.each do |spot| %>
            var marker = new google.maps.Marker({
              position:{lat: <%= spot.latitude %>, lng: <%= spot.longitude %>},
              map: map,
            });
            var infoWindow = new google.maps.InfoWindow({
              content: "<%= spot.address %>"
            });
            infoWindow.open(map, marker);
          <% end %>
        }
      </script>
      <script async src="https://maps.googleapis.com/maps/api/js?v=3.exp&key=<%= ENV['GOOGLE_API_KEY'] %>&callback=initMap"></script>
    </div>
    <div class="col-5 ml-3">
      <% note.spots.each do |spot| %>
      <div class="row mb-2">
        <div class="col-1">
          <i class="far fa-bookmark fa-2x float-right"></i>
        </div>
        <div class="col-10">
          <div class="spot-name"><b><%= spot.address %></b></div>
          <div class="show-spot-body mt-2 col-12"><%= spot.body %></div>
        </div>
      </div>
      <% end %>
    </div>
  <% end %>
</div>

app/views/notes/draft.html.erb
<div class="container mt-5 pb-5">
  <div class="row">
    <%= render 'users/info', user: current_user, notes: @user_notes %>
    <div class="col-8 ml-3">
      <h1><b style="color: #E08504;">下</b>書き</h1>
      <% if @notes.count == 0 %>
        <div>下書きありません</div>
      <% else %>
        <%= render 'notes/index', notes: @notes %>
      <% end %>
      <div class="row col-10 m-auto">
        <%= paginate @notes %> 
      </div>
    </div>
  </div>
</div>

app/views/notes/edit.html.erb
<div class="container mt-5 pb-5">
  <div class="row">
    <div class="col-8 m-auto">
      <h1><b style="color: #E08504;">投</b>稿の 
      <b style="color: #E08504;">編</b>集</h1>
      <%= render 'notes/edit', note: @note, tag_list: @tag_list %>
    </div>
  </div>
</div>

app/views/notes/index.html.erb
<div class="container mt-5 pb-3">
  <div class="row">
    <%= render 'searchs/form', tags: @tags, notes: @notes %>
    <div class="col-lg-8 col-sm-12 ml-lg-3">
      <h1><b style="color: #E08504;">投</b>稿一覧</h1>
      <%= render 'notes/index', notes: @notes %>
      
      <div class="row col-10 m-auto">
        <%= paginate @notes %> 
      </div>
    </div>
  </div>
</div>

app/views/notes/new.html.erb
<div class="container mt-5 pb-5">
  <div class="row">
    <div class="col-8 m-auto">
      <h1><b style="color: #E08504;">新</b>規投稿</h1>
      <%= render 'notes/form', note: @note %>
    </div>
  </div>
</div>

app/views/notes/show.html.erb
<div class="container mt-5 pb-5">
  <div class="row">
    <%= render 'users/info', user: @user, notes: @user_notes %>
    <div class="col-8 ml-3">
      <div class="border-bottom border-secondary mb-3">
        <h1><b style="color: #E08504;">投</b>稿の詳細</h1>
      </div>
      <div>
        <%= render 'notes/show', note: @note %>
      </div>
      <div class="mt-5">
        <h2 class="border-bottom border-secondary mb-3">コメント</h2>
        <%= render 'note_comments/form', note: @note, note_comment: @note_comment %>
      </div>
      <div id="comment_index">
        <%= render 'note_comments/index', note: @note %>
      </div>
    </div>
  </div>
</div>