config/routes.rb
Rails.application.routes.draw do
  root to: 'homes#top'
  devise_for :users
  devise_scope :user do
    post 'users/guest_sign_in' => 'users/sessions#new_guest'
  end

  get 'search' => "searchs#search", as: 'search'
  get 'search/tag/:tag_name' => "searchs#tag_search", as: 'tag_search'

  get 'mypage' => 'users#mypage', as: 'mypage'
  patch 'withdraw' => 'users#withdraw'
  get 'mypage/edit' => 'users#edit'
  patch 'mypage/update' => 'users#update'

  resources :users, only: [:show], param: :name do
    resource :relationship, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end

  put 'new/:id/post' => 'notes#post', as: 'notes_post'
  get 'favorite-notes' => 'users#favorite', as: 'favorite_notes'

  get 'notes/draft' => 'notes#draft', as: 'notes_draft'

  resources :notes do
    resources :note_comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
    resources :spots, only: [:new, :create, :destroy]
  end

  resources :notifications, only: :index
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  attachment :profile_image
  validates :name, uniqueness: true, presence: true, length: { minimum: 2, maximum: 10 }, format: { with: /\A[a-zA-Z0-9]+\z/ }
  validates :email, uniqueness: true

  has_many :notes, dependent: :destroy
  has_many :note_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  has_many :active_relationships,  class_name:  'Relationship', foreign_key: 'follower_id', dependent:   :destroy
  has_many :passive_relationships, class_name:  'Relationship', foreign_key: 'followed_id', dependent:   :destroy
  has_many :following, through: :active_relationships,  source: :followed
  has_many :followers, through: :passive_relationships, source: :follower

  has_many :active_notifications, class_name: 'Notification', foreign_key: 'visitor_id', dependent: :destroy
  has_many :passive_notifications, class_name: 'Notification', foreign_key: 'visited_id', dependent: :destroy

  def follow(user)
    active_relationships.create(followed_id: user.id)
  end

  def unfollow(user_name)
    user = User.find_by(name: user_name)
    active_relationships.find_by(followed_id: user.id).destroy
  end

  def following?(other_user)
    following.include?(other_user)
  end

  def to_param
    name
  end

  def self.search_for(word)
    User.where('name like?', "%#{word}%")
  end

  def self.guest
    find_or_create_by(name: 'Guest') do |user|
      user.email    = SecureRandom.alphanumeric(15) + '@email.com'
      user.password = SecureRandom.urlsafe_base64
      # user.confirmed_at = Time.now
    end
  end

  def active_for_authentication?
    super && (users_status == false)
  end

  def create_notification_follow(current_user)
    temp = Notification.where(["visitor_id = ? and visited_id = ? and action = ? ", current_user.id, id, 'follow'])
    if temp.blank?
      notification = current_user.active_notifications.new(
        visited_id: id,
        action: 'follow'
      )
      if notification.valid?
        notification.save
      end
    end
  end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  def new_guest
    user = User.guest
    sign_in user
    redirect_to root_path, notice: 'ゲストユーザーとしてログインしました'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def mypage
    @user = User.find(current_user.id)
    @user_notes = Note.user_notes_tag(@user)
    @notes = current_user.notes.private_public_note.page(params[:page]).per(4)
  end

  def show
    @user = User.find_by(name: params[:name])
    @user_notes = Note.user_notes_tag(@user)
    @notes = @user.notes.public_note.page(params[:page]).per(4)
  end

  def edit
    @user = User.find(current_user.id)
  end

  def update
    @user = User.find(current_user.id)
    if @user.update(user_params)
      flash[:notice] = 'プロフィールが変更されました'
      redirect_to mypage_path
    else
      render 'edit'
    end
  end

  def withdraw
    current_user.update(users_status: true)
    reset_session
    flash[:notice] = 'ありがとうございました。またのご利用を心よりお待ちしております。'
    redirect_to root_path
  end

  def favorite
    @user = User.find(current_user.id)
    favorites = Favorite.where(user_id: @user.id).pluck(:note_id)
    @favorites_notes = Note.includes(:user, :tags).find(favorites)
    @user_notes = Note.includes(:tags).where(user_id: @user.id).all
  end

  private

  def user_params
    params.require(:user).permit(:name, :profile_image, :email)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_index.html.erb
<table class="table tabel-hover table-inverse">
  <tbody>
    <% users.each do |user| %>
    <tr>
      <td>
        <div class="profile-img">
          <%= attachment_image_tag user, :profile_image, format: 'jpg', fallback: "no_image.jpg" %>
        </div>
        <%= link_to user.name, user_path(user.name) %>
      </td>
      <td>
        <% if user.users_status == true %>
          <span class="user-status border border-danger">
            退会済みユーザー
          </span>
        <% end %>
      </td>
      <td>
        <% if current_user != user %>
          <div class="text-center border border-secondary rounded-pill">
            <% if current_user.following?(user) %>
              <%= link_to "フォロー中", user_relationship_path(user.name), method: :delete %>
            <% else %>
              <%= link_to "フォローする", user_relationship_path(user.name), method: :post %>
            <% end %>
          </div>
        <% end %>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/users/_info.html.erb
<div class="col-lg-3 col-md-4 users-info">
  <% if user == current_user %>
    <div class=row>
      <%= link_to mypage_edit_path, class: "ml-2 col-2 btn btn-sm btn-secondary" do %>
        <i class="fas fa-cog"></i>
      <% end %>
    </div>
  <% end %>
  <% if user.users_status == true %>
    <span class="user-status border border-danger">
      退会済みユーザー
    </span>
  <% end %>
  <div class="usershow-profile-img m-auto">
    <%= attachment_image_tag user, :profile_image, format: 'jpg', fallback: "no_image.jpg", class:"rounded-circle" %>
  </div>
  <div class="my-2 text-center">
    <b><%= user.name %></b>
  </div>
  <% if user != current_user %>
    <div class="text-center follow">
      <% if current_user.following?(user) %>
        <%= link_to "フォロー中", user_relationship_path(user.name), method: :delete, class:"text-secondary" %>
      <% else %>
        <%= link_to "フォローする", user_relationship_path(user.name), method: :post %>
      <% end %>
    </div>
  <% end %>
  <table class="table my-4">
    <tbody>
      <tr>
        <th>フォロー中</th>
        <th><%= link_to user.following.count, user_followings_path(user.name), class:"text-secondary" %></th>
      </tr>
      <tr>
        <th>フォロワー</th>
        <th><%= link_to user.followers.count, user_followers_path(user.name), class:"text-secondary" %></th>
      </tr>
      <tr>
        <th>投稿</th>
        <th><%= link_to notes.count, user_path(user.name), class:"text-secondary" %></th>
      </tr>
      <% if user == current_user %>
        <tr>
          <th>お気に入り</th>
          <th><%= link_to user.favorites.count, favorite_notes_path, class:"text-secondary" %></th>
        </tr>
      <% end %>
    </tbody>
  </table>
  <div class="text-center my-tag">
    <div class="my-1">
      <% if user == current_user %>
        <b>Your Tag</b>
      <% else %>
        <b><%= user.name %>'s Tag</b>
      <% end %>
    </div>
    <div>
      <% if notes.exists? %>
        <% notes.each do |note| %>
          <% note.tags.each do |tag| %>
            <%= link_to tag.tag_name, tag_search_path(tag.tag_name), class:"text-secondary" %>
          <% end %>
        <% end %>
      <% else %>
        <p>Tagはまだありません</p>
      <% end %>
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<div class="container mt-5">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h2>ユーザー情報変更</h2>
      <%= form_with model:@user,url: mypage_update_path, method: :patch, local: true do |f| %>
      <div class="form-group mt-4">
        <%= f.label :name %><span class="mandatory border border-danger">必須</span><br />
        <%= f.text_field :name, autofocus: true, autocomplete: "name" %>
      </div>
      <div class="form-group row mt-3">
        <div class="col-6">
          <%= f.label :プロフィール画像 %><br />
          <%= f.attachment_field :profile_image, id: "profile_image" %>
        </div>
        <div class="profile-img-preview ml-5">
          <%= attachment_image_tag @user, :profile_image, fallback: "no_image.jpg", class: "card img-rounded" %>
        </div>
        <script>
        $(function() {
            $('#profile_image').on('change', function() {
                var selectedFile = this.files[0];
                var fileReader = new FileReader();
        
                fileReader.onload = function(event) {
                    var loadedImageUri = event.target.result;
                     $('.img-rounded').attr('src', loadedImageUri);
                };
        
                fileReader.readAsDataURL(selectedFile);
            });
        });
        </script>
      </div>
      <div class="form-group">
        <%= f.label :email, "メールアドレス" %><span class="mandatory border border-danger">必須</span>
        <%= f.email_field :email, autocomplete: "email", class:"input" %>
      </div>
      <div class="actions col-9 mx-auto mt-4">
        <%= f.submit "変更を確定する", class: "btn-block btn-sm btn btn-secondary" %>
      </div>
      <div class="actions col-9 mx-auto my-3">
        <%= link_to "退会する", withdraw_path, class: "text-center btn-block btn-sm btn btn-secondary", method: :patch, "data-confirm" => "本当に退会しますか？" %>
        <div class="text-center" style="font-size: 10px">※退会しても、投稿は削除されません。</div>
        <div class="text-center" style="font-size: 10px">※同一のユーザー名、メールアドレスでは再度登録出来なくなります。</div>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/favorite.html.erb
<div class="container py-5">
  <div class="row">
    <%= render 'users/info', user: @user, notes: @user_notes %>
    <div class="col-8 ml-3">
      <h1><b style="color: #E08504;">お</b>気に入り 
      <b style="color: #E08504;">投</b>稿</h1>
      <%= render 'notes/index', notes: @favorites_notes %>
    </div>
  </div>
</div>

app/views/users/mypage.html.erb
<div class="container mt-5 pb-5">
  <div class="row">
    <%= render 'users/info', user: current_user, notes: @user_notes %>
    <div class="col-lg-8 col-md-7 ml-3">
      <h1><b style="color: #E08504;">M</b>y <b style="color: #E08504;">P</b>age</h1>
      <% if @notes.count == 0 %>
        <div>投稿はありません</div>
      <% else %>
        <%= render 'notes/index', notes: @notes %>
      <% end %>
      <div class="row col-10 m-auto">
        <%= paginate @notes %> 
      </div>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container mt-5 pb-5">
  <div class="row">
    <%= render 'users/info', user: @user, notes: @user_notes %>
    <div class="col-8 ml-3">
      <h1><b><%= @user.name %></b>の<b style="color: #E08504;">投</b>稿</h1>
      <%= render 'notes/index', notes: @notes %>
    </div>
  </div>
</div>