config/routes.rb
Rails.application.routes.draw do
  root to: 'homes#top'
  devise_for :users
  devise_scope :user do
    post 'users/guest_sign_in' => 'users/sessions#new_guest'
  end

  get 'search' => "searchs#search", as: 'search'
  get 'search/tag/:tag_name' => "searchs#tag_search", as: 'tag_search'

  get 'mypage' => 'users#mypage', as: 'mypage'
  patch 'withdraw' => 'users#withdraw'
  get 'mypage/edit' => 'users#edit'
  patch 'mypage/update' => 'users#update'

  resources :users, only: [:show], param: :name do
    resource :relationship, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end

  put 'new/:id/post' => 'notes#post', as: 'notes_post'
  get 'favorite-notes' => 'users#favorite', as: 'favorite_notes'

  get 'notes/draft' => 'notes#draft', as: 'notes_draft'

  resources :notes do
    resources :note_comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
    resources :spots, only: [:new, :create, :destroy]
  end

  resources :notifications, only: :index
end

app/views/layouts/_errors.html.erb
<% if model.errors.any? %>
  <div class="border border-danger col-6">
    <% model.errors.full_messages.each do |message| %>
      <%= message %></br>
    <% end %>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
 <div class="container">
    <div class="row no-gutters">
      <div class="col-8 text-center my-3">
        <p>私のお気に入りSpot</p>
        <%= link_to "Travel Spot", root_path, class:"footer-brand text-white", data: {"turbolinks" => false} %>
      </div>
      <div class="col-4 my-3">
        <h6 class="text-white mt-2 mb-3">Menu</h6>
        <ul class="p-0 list-unstyled">
          <% if user_signed_in? %>
            <li>
              <%= link_to(mypage_path, class:"text-white-50") do %>
                <i class="fas fa-user-circle"></i><%= current_user.name %> Page
              <% end %>
            </li>
            <li><%= link_to "投稿一覧", notes_path, class:"text-white-50" %></li>
            <li><%= link_to "投稿作成", new_note_path, class:"text-white-50" %></li>
            <li><%= link_to "下書き", notes_draft_path, class:"text-white-50" %></li>
            <li><%= link_to "ログアウト", destroy_user_session_path, method: :delete, class:"text-white-50" %></li>
          <% else %>
            <li><%= link_to "ホーム", root_path, class:"text-white-50", data: {"turbolinks" => false}%></li>
            <li><%= link_to "新規登録", new_user_registration_path, class:"text-white-50" %></li>
            <li><%= link_to "ログイン", new_user_session_path, class:"text-white-50" %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_header.html.erb
<div class="shadow-sm">
  <nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav">
    <div class="container">
      <%= link_to "Travel Spot", root_path, class:"navbar-brand", data: {"turbolinks" => false} %>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        Menu
        <i class="fas fa-bars"></i>
      </button>
      <div class="collapse navbar-collapse justify-content-center" id="navbarNavDropdown">
        <ul class="navbar-nav ml-auto text-right">
          <% if user_signed_in? %>
            <li class="nav-item mx-2 px-2 rounded">
              <%= link_to(mypage_path, class: "text-secondary") do %>
                <i class="fas fa-user-circle"></i><%= current_user.name %> Page
              <% end %>
            </li>
            <li class="nav-item mx-2 px-2 rounded">
              <%= link_to(notifications_path, class: "mr-4 text-secondary") do %>
                <% if unchecked_notifications.any? %>
                  <i class="far fa-bell fa-lg" style="color: #FF0033"></i>通知(<%= unchecked_notifications.count %>)
                <% else %>
                  <i class="far fa-bell fa-lg"></i>通知
                <% end %>
              <% end %>
            </li>
            <li class="nav-item mx-2 px-2 rounded"><%= link_to "投稿一覧", notes_path, class:"text-secondary" %></li>
            <li class="nav-item mx-2 px-2 rounded"><%= link_to "新規投稿", new_note_path, class:"text-secondary" %></li>
            <li class="nav-item mx-2 px-2 rounded"><%= link_to "下書き", notes_draft_path, class:"text-secondary" %></li>
            <li class="nav-item mx-2 px-2 rounded"><%= link_to "ログアウト", destroy_user_session_path, method: :delete, class:"text-secondary" %></li>
          <% else %>
            <li><%= flash[:notice] %></li>
            <li class="nav-item mx-2 px-2 rounded"><%= link_to "ホーム", root_path, class:"text-secondary", data: {"turbolinks" => false} %></li>
            <li class="nav-item mx-2 px-2 rounded"><%= link_to "新規登録", new_user_registration_path, class:"text-secondary" %></li>
            <li class="nav-item mx-2 px-2 rounded"><%= link_to "ログイン", new_user_session_path, class:"text-secondary" %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TravelSpot</title>
    <meta charset="UTF-8" />
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width,initial-scale=1.0">
    
    <%= include_gon %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Caveat" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Outfit&display=swap" rel="stylesheet">
  </head>

  <body>
    <header>
      <%= render "layouts/header" %>
    </header>
    <main>
      <%= yield %>
      <span id="back">
        <a href="#">
          <i class="fas fa-arrow-circle-up fa-3x"></i></br>
        </a>
      </span>
    </main>
    <footer>
      <%= render "layouts/footer" %>
    </footer>
  </body>
</html>